steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/literary-app', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/literary-app']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'literary-app'
    - '--image'
    - 'gcr.io/$PROJECT_ID/literary-app'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'CLOUD_SQL_CONNECTION_NAME=$PROJECT_ID:us-central1:literary-db'
    - '--set-env-vars'
    - 'DB_USER=literary-user'
    - '--set-env-vars'
    - 'DB_NAME=literary_app'
    - '--set-secrets'
    - 'SECRET_KEY=flask-secret-key:latest'
    - '--set-secrets'
    - 'DB_PASS=db-password:latest'
    - '--set-secrets'
    - 'ANTHROPIC_API_KEY=anthropic-api-key:latest'
    - '--set-secrets'
    - 'OPENAI_API_KEY=openai-api-key:latest'

images:
  - 'gcr.io/$PROJECT_ID/literary-app'

timeout: 1800s
